################################# Default configuration ###################
baseURL = "https://pedantic-swartz-f1ece7.netlify.com"
title = "nta blog"
theme = "airspace-hugo"
# post pagination
paginate = "4"
# post excerpt
summaryLength = "30"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com

languageName = "Japanese"
languageCode = "ja-jp"

home = "Home"

#################################### Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"

  
############################## navigation ###############################

# main menu
[[menu.main]]
name = "About"
URL = "about"
weight = 1

[[menu.main]]
name = "Blog"
URL = "blog"
weight = 2

[[menu.main]]
weight = 3
name = "Category"
hasChildren = true

  [[menu.main]]
  parent = "Category"
  name = "Categories"
  URL = "categories"

  [[menu.main]]
  parent = "Category"
  name = "Tags"
  URL = "tags"

# footer menu
[[menu.footer]]
name = "About"
URL = "about"
weight = 1

[[menu.footer]]
name = "Blog"
URL = "blog"
weight = 2

[[menu.footer]]
name = "Categories"
URL = "categories"
weight = 3

[[menu.footer]]
name = "Tags"
URL = "tags"
weight = 4

#################### default parameters ################################
[params]
logo = "images/logo.png"
# Meta data
description = "This is meta description"
author = "Themefisher"
# Contact Information
mobile = "0124857985320"
email = "demo@email.com"
location = "North Main Street,Brooklyn Australia"
# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io
# Google Analitycs
google_analitycs_id = "" # Your ID

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# search
[params.search]
enable = true

# Navigation get start button
[params.nav_button]
enable = true
label = "Get A Quote"
link = "contact"

# google map
[params.gmap]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

  
############################# social site ########################
[[params.social]]
icon = "ion-social-googleplus-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-linkedin-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-pinterest-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-dribbble-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-twitter-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-facebook-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

copyright = "Copyright &copy; 2019 [Themefisher](https://themefisher.com) All Rights Reserved"
